meta:
  source: backtest_filtered
  period: 2025-10-17 ~ 2026-04-07
  criteria: PF>=1.5, trades>=10
  count: 6
stocks:
- ticker: '277810'
  name: 레인보우로보틱스
- ticker: '475150'
  name: SK이터닉스
- ticker: '047040'
  name: 대우건설
- ticker: 080220
  name: 제주반도체
- ticker: '042700'
  name: 한미반도체
- ticker: 009830
  name: 한화솔루션
